<?xml version="1.0" encoding="UTF-8"?>
<ActionCollection version="2" name="Scripts">
    <Actions category="Scripts">
        <text>Export Layers Auto</text>

        <Action name="export-layers-auto-current">
            <icon></icon>
            <text>Export Layers Auto (Current)</text>
            <whatsThis></whatsThis>
            <toolTip>Trigger export layers plugin for current document</toolTip>
            <iconText></iconText>
            <activationFlags>0</activationFlags>
            <activationConditions>0</activationConditions>
            <shortcut></shortcut>
            <isCheckable>false</isCheckable>
            <statusTip></statusTip>
        </Action>

        <Action name="export-layers-auto-all">
            <icon></icon>
            <text>Export Layers Auto (All Documents)</text>
            <whatsThis></whatsThis>
            <toolTip>Trigger export layers plugin for all open documents</toolTip>
            <iconText></iconText>
            <activationFlags>0</activationFlags>
            <activationConditions>0</activationConditions>
            <shortcut></shortcut>
            <isCheckable>false</isCheckable>
            <statusTip></statusTip>
        </Action>
    </Actions>
</ActionCollection>
