<?xml version="1.0" encoding="UTF-8"?>
<ActionCollection version="2" name="Scripts">
    <Actions category="Scripts">
        <text>Export Layers Auto</text>

        <Action name="export-layers-auto">
        <icon></icon>
        <text>Export Layers Auto</text>
        <whatsThis></whatsThis>
        <toolTip>Trigger export layers auto in the background</toolTip>
        <iconText></iconText>
        <activationFlags>0</activationFlags>
        <activationConditions>0</activationConditions>
        <shortcut></shortcut>
        <isCheckable>false</isCheckable>
        <statusTip></statusTip>
        </Action>
    </Actions>
</ActionCollection>
